using System;
using System.Collections.Generic;

namespace Haste {

  // Which asset paths the Project source skips.
  //
  // Rules come from three places, unioned: the built-in list below, a list committed with
  // the project (HasteIgnorePaths), and the user's own additions in EditorPrefs. Pure and
  // static so the matching can be tested; the storage lives elsewhere.
  public static class HasteIgnoreRules {

    // A rule containing "/" is a PATH PREFIX rooted at the project: "Assets/Plugins"
    // matches that folder and everything under it, and nothing else.
    //
    // A rule with no "/" is a FOLDER NAME matched at any depth: "Firebase" catches
    // Assets/Firebase and Assets/Plugins/Firebase alike. Vendored SDKs land wherever the
    // importer felt like putting them, so a fixed path would miss half of them.
    //
    // A rule starting with "!" is an EXCEPTION and wins over any match. That is what keeps
    // Plugins/Android/AndroidManifest.xml findable while the rest of Plugins is ignored.
    public const char NegationPrefix = '!';

    // Shipped defaults. Limited to things that are machine-generated or vendored by
    // convention -- never a folder a project puts its own work in.
    //
    // Every rule here is PATH-ROOTED, even though bare names would catch an SDK wherever
    // it was unpacked. That was the first attempt and it was wrong: measured against a
    // real 20,000-file project, a bare "Firebase" also hid
    // Assets/Scripts/Firebase/FirebaseService.cs -- the project's OWN wrapper code, named
    // after the SDK it wraps, which is completely normal. A shipped list cannot see the
    // project's layout, so it has no business guessing at any depth. Bare names stay
    // available for rules a user adds, where they can see what they are matching.
    public static readonly string[] Builtin = {
      // Third-party code, by convention. Every Unity project treats Plugins this way.
      "Assets/Plugins",

      // ...except the platform folders, which hold build inputs people really do search
      // for: AndroidManifest.xml, Info.plist additions, native .mm files.
      "!Assets/Plugins/Android",
      "!Assets/Plugins/iOS",
      "!Assets/Plugins/tvOS",

      // Purely generated by Google's External Dependency Manager.
      "Assets/ExternalDependencyManager",
      "Assets/GeneratedLocalRepo",
      "Assets/PlayServicesResolver",

      // Vendored SDKs, at the root where their importers put them.
      "Assets/Firebase",
      "Assets/GoogleMobileAds",
      "Assets/GooglePlayGames",
      "Assets/FacebookSDK",
      "Assets/AppleAuth",
      "Assets/TextMesh Pro",

      // Unity magic folders: editor chrome, not project content.
      "Assets/Editor Default Resources",
      "Assets/Gizmos",
    };

    public static bool IsIgnored(string assetPath, IList<string> rules) {
      if (string.IsNullOrEmpty(assetPath) || rules == null || rules.Count == 0) {
        return false;
      }

      var ignored = false;

      for (int i = 0; i < rules.Count; i++) {
        var rule = rules[i];
        if (string.IsNullOrEmpty(rule)) {
          continue;
        }

        var negated = rule[0] == NegationPrefix;
        if (negated) {
          rule = rule.Substring(1);
          if (rule.Length == 0) {
            continue;
          }
        }

        if (!RuleMatches(assetPath, rule)) {
          continue;
        }

        // An exception wins outright, wherever it appears in the list, so order does not
        // have to be reasoned about.
        if (negated) {
          return false;
        }

        ignored = true;
      }

      return ignored;
    }

    static bool RuleMatches(string assetPath, string rule) {
      rule = rule.Trim().TrimEnd('/');
      if (rule.Length == 0) {
        return false;
      }

      // Ordinal throughout, per HANDOFF 6.3: these are paths, and culture-sensitive
      // comparison genuinely diverges in tr-TR. IgnoreCase because the rules are typed by
      // hand and most of the filesystems under them are case-insensitive anyway.
      if (rule.IndexOf('/') >= 0) {
        if (!assetPath.StartsWith(rule, StringComparison.OrdinalIgnoreCase)) {
          return false;
        }
        // Require a segment boundary, or "Assets/Plugins" silently swallows
        // "Assets/PluginsCustom".
        return assetPath.Length == rule.Length || assetPath[rule.Length] == '/';
      }

      return HasSegment(assetPath, rule);
    }

    static bool HasSegment(string assetPath, string segment) {
      int start = 0;

      while (start <= assetPath.Length) {
        var end = assetPath.IndexOf('/', start);
        if (end < 0) {
          end = assetPath.Length;
        }

        if (end - start == segment.Length &&
            string.Compare(assetPath, start, segment, 0, segment.Length,
                           StringComparison.OrdinalIgnoreCase) == 0) {
          return true;
        }

        start = end + 1;
      }

      return false;
    }

    // Splits the comma-separated form the user's own list is stored in.
    public static string[] Parse(string commaSeparated) {
      if (string.IsNullOrEmpty(commaSeparated)) {
        return new string[0];
      }

      var parts = commaSeparated.Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries);
      var rules = new List<string>(parts.Length);
      foreach (var part in parts) {
        var trimmed = part.Trim();
        if (trimmed.Length > 0) {
          rules.Add(trimmed);
        }
      }
      return rules.ToArray();
    }
  }
}
