using System.IO;
using System.Linq;
using NUnit.Framework;
using UnityEditor;
using UnityEngine;

namespace Haste {

  // Pins the prefab semantics Haste depends on, after the migration off PrefabType.
  //
  // Unity 2018.3 split one question ("what sort of prefab is this?") into two ("what kind
  // of asset is it?" and "what is this instance's relationship to its asset?"), and the
  // obvious-looking replacement is the wrong one: GetPrefabAssetType answers "Regular" for
  // an instance as well as for the asset it came from. Everything below was generated by
  // running against real objects on 6000.3.17f1, not derived.
  //
  // The fixtures are built here rather than pointed at Assets/Testing, so the suite also
  // passes in a project that only has the package.
  [TestFixture]
  internal class HastePrefabTests {

    const string TempFolder = "Assets/HasteTempPrefabFixtures";
    const string PrefabPath = TempFolder + "/HasteFixture.prefab";

    GameObject asset;
    GameObject instance;
    GameObject plain;

    [SetUp]
    public void SetUp() {
      if (!AssetDatabase.IsValidFolder(TempFolder)) {
        AssetDatabase.CreateFolder("Assets", "HasteTempPrefabFixtures");
      }

      var source = new GameObject("HasteFixture");
      asset = PrefabUtility.SaveAsPrefabAsset(source, PrefabPath);
      Object.DestroyImmediate(source);

      instance = PrefabUtility.InstantiatePrefab(asset) as GameObject;
      plain = new GameObject("HastePlainFixture");
    }

    [TearDown]
    public void TearDown() {
      if (instance != null) Object.DestroyImmediate(instance);
      if (plain != null) Object.DestroyImmediate(plain);
      AssetDatabase.DeleteAsset(TempFolder);
      AssetDatabase.Refresh();
    }

    [Test]
    public void PrefabApis_AnswerWhatTheMigrationAssumes() {
      Assert.That(asset, Is.Not.Null, "fixture prefab asset was not created");
      Assert.That(instance, Is.Not.Null, "fixture prefab instance was not created");

      // The trap, stated as an assertion: asset type does NOT distinguish an asset from
      // an instance. Anything that migrates a PrefabType check to GetPrefabAssetType is
      // wrong, and this is why.
      Assert.That(PrefabUtility.GetPrefabAssetType(asset), Is.EqualTo(PrefabAssetType.Regular));
      Assert.That(PrefabUtility.GetPrefabAssetType(instance), Is.EqualTo(PrefabAssetType.Regular));

      // What actually distinguishes them.
      Assert.That(PrefabUtility.IsPartOfPrefabAsset(asset), Is.True);
      Assert.That(PrefabUtility.IsPartOfPrefabAsset(instance), Is.False);
      Assert.That(PrefabUtility.IsPartOfPrefabAsset(plain), Is.False);

      Assert.That(PrefabUtility.GetPrefabInstanceStatus(asset), Is.EqualTo(PrefabInstanceStatus.NotAPrefab));
      Assert.That(PrefabUtility.GetPrefabInstanceStatus(instance), Is.EqualTo(PrefabInstanceStatus.Connected));
      Assert.That(PrefabUtility.GetPrefabInstanceStatus(plain), Is.EqualTo(PrefabInstanceStatus.NotAPrefab));
    }

    [Test]
    public void Classify_ColoursInstancesAsPrefabsAndNothingElse() {
      // Replaces the PrefabType switch that coloured hierarchy rows. A prefab ASSET is
      // deliberately Normal: it is never shown by the hierarchy source at all.
      Assert.That(HasteHierarchyResult.ClassifyPrefab(instance),
        Is.EqualTo(HasteHierarchyResult.PrefabDisplay.Prefab));
      Assert.That(HasteHierarchyResult.ClassifyPrefab(plain),
        Is.EqualTo(HasteHierarchyResult.PrefabDisplay.Normal));
      Assert.That(HasteHierarchyResult.ClassifyPrefab(asset),
        Is.EqualTo(HasteHierarchyResult.PrefabDisplay.Normal));

      // A destroyed or missing object must classify, not throw -- results outlive the
      // objects they point at.
      Assert.That(HasteHierarchyResult.ClassifyPrefab(null),
        Is.EqualTo(HasteHierarchyResult.PrefabDisplay.Normal));
    }

    [Test]
    public void APrefabAssetInTheProjectIsNotTintedLikeAnInactiveObject() {
      // A prefab ASSET reports activeInHierarchy == false, because it is not in a scene at
      // all -- not because it is disabled. AssetDatabase.LoadMainAssetAtPath returns its
      // root GameObject, so a row that decides tinting from "is this a GameObject?" greys
      // out every prefab in the Project results. Deciding from the SOURCE does not.
      Assert.That(asset.activeInHierarchy, Is.False, "the trap this test exists for");

      var projectItem = new HasteItem(PrefabPath, 0, HasteProjectSource.NAME);
      Assert.That(HasteKinds.UsesHierarchyTint(projectItem), Is.False);

      var hierarchyItem = new HasteItem("Main Camera", 0, HasteHierarchySource.NAME);
      Assert.That(HasteKinds.UsesHierarchyTint(hierarchyItem), Is.True);

      // Menu items and layouts have no object to tint from either.
      Assert.That(HasteKinds.UsesHierarchyTint(
        new HasteItem("File/Build Profiles", 0, HasteMenuItemSource.NAME)), Is.False);
      Assert.That(HasteKinds.UsesHierarchyTint(null), Is.False);
    }

    [Test]
    public void HierarchySource_SkipsPrefabAssetsButKeepsInstances() {
      // Resources.FindObjectsOfTypeAll returns prefab assets as well as scene objects, and
      // the Project source already indexes those.
      var paths = new HasteHierarchySource().Select(i => i.path).ToArray();

      Assert.That(paths, Contains.Item("HastePlainFixture"),
        "a plain scene object should be indexed");
      Assert.That(paths, Contains.Item("HasteFixture"),
        "a prefab INSTANCE is a scene object and should be indexed");

      // The asset and the instance share a name, so count rather than look for absence:
      // exactly one of the two must have been yielded.
      Assert.That(paths.Count(p => p == "HasteFixture"), Is.EqualTo(1),
        "the prefab asset was indexed alongside its instance");
    }
  }
}
